name: easybfe
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - pip
  - numpy
  - pandas
  - matplotlib
  - scipy
  - rich-click
  - parmed
  - openbabel
  - openmm>=8.2.0,<8.3.0
  - alchemlyb
  - spyrmsd
  - rdkit
  - pdbfixer
  - pydantic>=2.0
  - meeko>=0.7.0
  - gemmi
  - acpype
  - alchemlyb
  - ambertools
  - vina
  - openfe>=1.6.0
  - plip
  - pytest
  - pytest-cov
  - pip:
      # Docs dependencies (replaces [project.optional-dependencies].docs)
      - sphinx>=5.0.0
      - sphinx-rtd-theme>=1.0.0
      - sphinx-autodoc-typehints>=1.19.0
      - autodoc_pydantic>=1.8.0