"""
Tests for easybfe.ligand module.

This module tests the Ligand class and LigandLoader class functionality.
"""
import shutil
import tempfile
from pathlib import Path
import pytest
import pandas as pd
from rdkit import Chem

from easybfe.core.ligand import Ligand, LigandLoader


@pytest.fixture
def test_data_dir():
    """Return the path to the test data directory."""
    return Path(__file__).parent / 'data'


@pytest.fixture
def test_ligand_sdf(test_data_dir):
    """Return path to a test ligand SDF file."""
    return test_data_dir / 'benzene.sdf'


@pytest.fixture
def test_ligand_sdf_2(test_data_dir):
    """Return path to another test ligand SDF file."""
    return test_data_dir / 'chlorobenzene.sdf'


@pytest.fixture
def temp_dir():
    """Create a temporary directory for testing and clean up after."""
    temp_dir = tempfile.mkdtemp()
    yield Path(temp_dir)
    if Path(temp_dir).is_dir():
        shutil.rmtree(temp_dir)


class TestLigand:
    """Test Ligand class."""
    
    def test_ligand_creation(self):
        """Test creating a Ligand object with all required fields."""
        ligand = Ligand(
            name="benzene",
            smiles="c1ccccc1",
        )
        
        assert ligand.name == "benzene"
        assert ligand.smiles == "c1ccccc1"
        assert ligand.mol_block != ""
        assert ligand.auxiliary_files == {}
    
    def test_ligand_creation_with_aux_files(self):
        """Test creating a Ligand object with auxiliary files."""
        ligand = Ligand(
            name="benzene",
            smiles="c1ccccc1",
            mol_block="test mol block",
            source="test.sdf",
            auxiliary_files={"ligand.prmtop": "prmtop content"}
        )
        
        assert ligand.auxiliary_files == {"ligand.prmtop": "prmtop content"}
    
    def test_add_aux_file(self):
        """Test adding auxiliary files to a ligand."""
        ligand = Ligand(
            name="benzene",
            smiles="c1ccccc1",
            mol_block="test mol block",
            source="test.sdf"
        )
        
        ligand.add_aux_file("ligand.prmtop", "prmtop content")
        ligand.add_aux_file("ligand.inpcrd", "inpcrd content")
        
        assert ligand.auxiliary_files == {
            "ligand.prmtop": "prmtop content",
            "ligand.inpcrd": "inpcrd content"
        }
    
    def test_add_aux_file_overwrite(self):
        """Test that adding an auxiliary file with existing name overwrites."""
        ligand = Ligand(
            name="benzene",
            smiles="c1ccccc1",
            mol_block="test mol block",
            source="test.sdf"
        )
        
        ligand.add_aux_file("ligand.prmtop", "old content")
        ligand.add_aux_file("ligand.prmtop", "new content")
        
        assert ligand.auxiliary_files == {"ligand.prmtop": "new content"}


class TestLigandLoader:
    """Test LigandLoader class."""
    
    def test_loader_init(self):
        """Test LigandLoader initialization."""
        loader = LigandLoader()
        assert loader is not None
    
    def test_load_from_sdf_file(self, test_ligand_sdf):
        """Test loading ligands from an SDF file."""
        loader = LigandLoader()
        ligands = loader.load(test_ligand_sdf)
        
        assert len(ligands) == 1
        ligand = ligands[0]
        assert ligand.name == "benzene"
        assert "c1ccccc1" == ligand.smiles  # SMILES may vary in canonicalization
        assert ligand.mol_block != ""  # Should have mol block from SDF
        assert ligand.source == test_ligand_sdf.name
        assert isinstance(ligand.mol_block, str)
        
        # Verify mol_block matches what would be generated by direct loading
        suppl = Chem.SDMolSupplier(str(test_ligand_sdf), removeHs=False)
        mol = next(suppl)
        expected_mol_block = Chem.MolToMolBlock(mol)
        assert ligand.mol_block == expected_mol_block
    
    def test_load_from_sdf_with_name_from_stem(self, test_ligand_sdf):
        """Test loading from SDF with name_from_stem option (only works for list of paths)."""
        loader = LigandLoader()
        # name_from_stem only works when a list of paths is provided
        ligands = loader.load([test_ligand_sdf], name_from_stem=True)
        
        assert len(ligands) == 1
        # Name should be "benzene" (either from stem or _Name property)
        assert ligands[0].name == "benzene"
        
        # Verify mol_block matches what would be generated by direct loading
        suppl = Chem.SDMolSupplier(str(test_ligand_sdf), removeHs=False)
        mol = next(suppl)
        expected_mol_block = Chem.MolToMolBlock(mol)
        assert ligands[0].mol_block == expected_mol_block
    
    def test_load_from_sdf_single_path_ignores_name_from_stem(self, test_ligand_sdf):
        """Test that name_from_stem is ignored for single path (uses _Name property)."""
        loader = LigandLoader()
        # Even if name_from_stem=True, single path uses _Name property
        ligands = loader.load(test_ligand_sdf, name_from_stem=True)
        
        assert len(ligands) == 1
        # Should use _Name property from SDF, not filename stem
        assert ligands[0].name == "benzene"  # This might still match, but for different reason
    
    def test_load_from_sdf_only_first(self, temp_dir, test_ligand_sdf, test_ligand_sdf_2):
        """Test loading only first molecule from SDF."""
        loader = LigandLoader()
        
        # Create a multi-molecule SDF file
        suppl1 = Chem.SDMolSupplier(str(test_ligand_sdf), removeHs=False)
        suppl2 = Chem.SDMolSupplier(str(test_ligand_sdf_2), removeHs=False)
        
        multi_sdf = temp_dir / "multi_ligands.sdf"
        with Chem.SDWriter(str(multi_sdf)) as writer:
            for mol in suppl1:
                if mol is not None:
                    writer.write(mol)
            for mol in suppl2:
                if mol is not None:
                    writer.write(mol)
        
        # Load all molecules
        ligands_all = loader.load(multi_sdf)
        assert len(ligands_all) >= 1
        
        # Load only first
        ligands_first = loader.load(multi_sdf, only_first=True)
        assert len(ligands_first) == 1
    
    def test_load_from_csv(self, temp_dir):
        """Test loading ligands from a CSV file."""
        # Create a CSV file
        csv_file = temp_dir / "ligands.csv"
        df = pd.DataFrame({
            "Name": ["benzene", "toluene"],
            "SMILES": ["c1ccccc1", "Cc1ccccc1"]
        })
        df.to_csv(csv_file, index=False)
        
        loader = LigandLoader()
        ligands = loader.load(csv_file, name_col="Name", smi_col="SMILES")
        
        assert len(ligands) == 2
        assert ligands[0].name == "benzene"
        assert ligands[1].name == "toluene"
        assert ligands[0].mol_block  # CSV doesn't have 3D geometry
        assert ligands[0].source == csv_file.name
    
    def test_load_from_csv_missing_columns(self, temp_dir):
        """Test that loading from CSV with missing columns raises KeyError."""
        csv_file = temp_dir / "ligands.csv"
        df = pd.DataFrame({
            "Name": ["benzene"],
            "SMILES": ["c1ccccc1"]
        })
        df.to_csv(csv_file, index=False)
        
        loader = LigandLoader()
        with pytest.raises(KeyError):
            loader.load(csv_file, name_col="invalid_col", smi_col="SMILES")
    
    def test_load_from_csv_missing_kwargs(self, temp_dir):
        """Test that loading from CSV without required kwargs raises ValueError."""
        csv_file = temp_dir / "ligands.csv"
        df = pd.DataFrame({
            "Name": ["benzene"],
            "SMILES": ["c1ccccc1"]
        })
        df.to_csv(csv_file, index=False)
        
        loader = LigandLoader()
        with pytest.raises(ValueError):
            loader.load(csv_file)
    
    def test_load_from_smiles_file(self, temp_dir):
        """Test loading ligands from a SMILES file."""
        # Create a SMILES file
        smi_file = temp_dir / "ligands.smi"
        with open(smi_file, 'w') as f:
            f.write("c1ccccc1 benzene\n")
            f.write("Cc1ccccc1 toluene\n")
        
        loader = LigandLoader()
        ligands = loader.load(smi_file)
        
        assert len(ligands) == 2
        assert ligands[0].name == "benzene"
        assert ligands[1].name == "toluene"
        assert ligands[0].mol_block  # SMILES file doesn't have 3D geometry
        assert ligands[0].source == smi_file.name
    
    def test_load_from_smiles_file_no_names(self, temp_dir):
        """Test loading from SMILES file without names."""
        smi_file = temp_dir / "ligands.smi"
        with open(smi_file, 'w') as f:
            f.write("c1ccccc1\n")
            f.write("Cc1ccccc1\n")
        
        loader = LigandLoader()
        ligands = loader.load(smi_file)
        
        assert len(ligands) == 2
        assert ligands[0].name.startswith("ligands_line_1")
        assert ligands[1].name.startswith("ligands_line_2")
    
    def test_load_from_smiles_file_with_comments(self, temp_dir):
        """Test that comments in SMILES file are ignored."""
        smi_file = temp_dir / "ligands.smi"
        with open(smi_file, 'w') as f:
            f.write("# This is a comment\n")
            f.write("c1ccccc1 benzene\n")
            f.write("# Another comment\n")
        
        loader = LigandLoader()
        ligands = loader.load(smi_file)
        
        assert len(ligands) == 1
        assert ligands[0].name == "benzene"
    
    def test_load_from_dataframe(self):
        """Test loading ligands from a pandas DataFrame."""
        df = pd.DataFrame({
            "Name": ["benzene", "toluene"],
            "SMILES": ["c1ccccc1", "Cc1ccccc1"]
        })
        
        loader = LigandLoader()
        ligands = loader.load(df, name_col="Name", smi_col="SMILES")
        
        assert len(ligands) == 2
        assert ligands[0].name == "benzene"
        assert ligands[1].name == "toluene"
        assert ligands[0].mol_block  # DataFrame doesn't have 3D geometry
        assert ligands[0].source == "DataFrame"
    
    def test_load_from_dataframe_missing_columns(self):
        """Test that loading from DataFrame with missing columns raises KeyError."""
        df = pd.DataFrame({
            "Name": ["benzene"],
            "SMILES": ["c1ccccc1"]
        })
        
        loader = LigandLoader()
        with pytest.raises(KeyError):
            loader.load(df, name_col="invalid_col", smi_col="SMILES")
    
    def test_load_from_rdkit_molecules(self):
        """Test loading ligands from a list of RDKit molecules."""
        mol1 = Chem.MolFromSmiles("c1ccccc1")
        mol1.SetProp("_Name", "benzene")
        mol2 = Chem.MolFromSmiles("Cc1ccccc1")
        mol2.SetProp("_Name", "toluene")
        
        loader = LigandLoader()
        ligands = loader.load([mol1, mol2])
        
        assert len(ligands) == 2
        assert ligands[0].name == "benzene"
        assert ligands[1].name == "toluene"
        # Source is not set for RDKit molecules in the current implementation
        assert isinstance(ligands[0].mol_block, str)
        assert ligands[0].mol_block != ""  # MolToMolBlock generates mol block even without 3D coords
    
    def test_load_from_rdkit_molecules_with_3d(self):
        """Test loading from RDKit molecules with 3D coordinates."""
        from rdkit.Chem import AllChem
        
        mol = Chem.MolFromSmiles("c1ccccc1")
        mol = Chem.AddHs(mol)
        AllChem.EmbedMolecule(mol)
        AllChem.MMFFOptimizeMolecule(mol)
        mol.SetProp("_Name", "benzene")
        
        loader = LigandLoader()
        ligands = loader.load([mol])
        
        assert len(ligands) == 1
        assert ligands[0].name == "benzene"
        # Should have mol_block if 3D coordinates exist
        assert isinstance(ligands[0].mol_block, str)
    
    def test_load_from_rdkit_molecules_no_name(self):
        """Test that loading from RDKit molecules without _Name property raises ValueError."""
        mol1 = Chem.MolFromSmiles("c1ccccc1")
        mol2 = Chem.MolFromSmiles("Cc1ccccc1")
        
        loader = LigandLoader()
        # Molecules without _Name property will have empty name, which will fail validation
        with pytest.raises(ValueError):
            loader.load([mol1, mol2])
    
    def test_load_from_list_of_files(self, test_ligand_sdf, test_ligand_sdf_2):
        """Test loading from a list of file paths."""
        loader = LigandLoader()
        ligands = loader.load([test_ligand_sdf, test_ligand_sdf_2])
        
        assert len(ligands) == 2
        assert ligands[0].source == test_ligand_sdf.name
        assert ligands[1].source == test_ligand_sdf_2.name
    
    def test_load_file_not_found(self, temp_dir):
        """Test that loading a non-existent file raises FileNotFoundError."""
        loader = LigandLoader()
        fake_file = temp_dir / "nonexistent.sdf"
        
        with pytest.raises(FileNotFoundError):
            loader.load(fake_file)
    
    def test_load_unsupported_format(self, temp_dir):
        """Test that loading an unsupported file format raises ValueError."""
        fake_file = temp_dir / "test.xyz"
        fake_file.write_text("fake content")
        
        loader = LigandLoader()
        with pytest.raises(ValueError):
            loader.load(fake_file)
    
    def test_load_unsupported_input_type(self):
        """Test that loading an unsupported input type raises ValueError."""
        loader = LigandLoader()
        with pytest.raises(ValueError):
            loader.load(12345)  # Integer is not supported
    
    def test_validate_uniqueness(self):
        """Test that duplicate names raise ValueError."""
        loader = LigandLoader()
        
        ligand1 = Ligand(
            name="benzene",
            smiles="c1ccccc1",
            mol_block="",
            source="test1.sdf"
        )
        ligand2 = Ligand(
            name="benzene",  # Duplicate name
            smiles="c1ccccc1",
            mol_block="",
            source="test2.sdf"
        )
        
        with pytest.raises(ValueError):
            loader._validate_uniqueness([ligand1, ligand2])
    
    def test_validate_uniqueness_passes(self):
        """Test that unique names pass validation."""
        loader = LigandLoader()
        
        ligand1 = Ligand(
            name="benzene",
            smiles="c1ccccc1",
            mol_block="",
            source="test1.sdf"
        )
        ligand2 = Ligand(
            name="toluene",
            smiles="Cc1ccccc1",
            mol_block="",
            source="test2.sdf"
        )
        
        # Should not raise
        loader._validate_uniqueness([ligand1, ligand2])
    
    def test_load_enforce_unique_name_true(self):
        """Test that enforce_unique_name=True (default) validates uniqueness."""
        loader = LigandLoader()
        
        df = pd.DataFrame({
            "Name": ["benzene", "benzene"],  # Duplicate names
            "SMILES": ["c1ccccc1", "c1ccccc1"]
        })
        
        with pytest.raises(ValueError):
            loader.load(df, name_col="Name", smi_col="SMILES")
    
    def test_load_enforce_unique_name_false(self):
        """Test that enforce_unique_name=False skips uniqueness validation."""
        loader = LigandLoader()
        
        df = pd.DataFrame({
            "Name": ["benzene", "benzene"],  # Duplicate names
            "SMILES": ["c1ccccc1", "c1ccccc1"]
        })
        
        # Should not raise when enforce_unique_name=False
        ligands = loader.load(df, name_col="Name", smi_col="SMILES", enforce_unique_name=False)
        assert len(ligands) == 2
        assert ligands[0].name == "benzene"
        assert ligands[1].name == "benzene"
    
    def test_load_from_csv_skips_empty_rows(self, temp_dir):
        """Test that empty rows in CSV are skipped."""
        csv_file = temp_dir / "ligands.csv"
        df = pd.DataFrame({
            "Name": ["benzene", "toluene"],
            "SMILES": ["c1ccccc1", "Cc1ccccc1"]
        })
        # Add rows with NaN values (which is what empty strings become in CSV)
        import numpy as np
        df.loc[len(df)] = [np.nan, "invalid"]  # Row with empty name
        df.loc[len(df)] = ["  ", np.nan]  # Row with empty SMILES
        
        df.to_csv(csv_file, index=False)
        
        loader = LigandLoader()
        ligands = loader.load(csv_file, name_col="Name", smi_col="SMILES")
        
        # Should only load benzene and toluene, skip empty rows
        assert len(ligands) == 2
        assert ligands[0].name == "benzene"
        assert ligands[1].name == "toluene"
    
    def test_load_from_sdf_loads_molecule(self, test_ligand_sdf):
        """Test that SDF loading loads molecules correctly."""
        loader = LigandLoader()
        ligands = loader.load(test_ligand_sdf)
        
        assert len(ligands) == 1
        ligand = ligands[0]
        
        # Check that mol_block is generated
        mol = Chem.MolFromMolBlock(ligand.mol_block)
        assert mol is not None
        assert ligand.mol_block != ""
        
        # Verify mol_block matches what would be generated by direct loading
        suppl = Chem.SDMolSupplier(str(test_ligand_sdf), removeHs=False)
        expected_mol = next(suppl)
        expected_mol_block = Chem.MolToMolBlock(expected_mol)
        assert ligand.mol_block == expected_mol_block
    
    def test_load_from_pathlib_path(self, test_ligand_sdf):
        """Test that Path objects work the same as strings."""
        loader = LigandLoader()
        
        # Test with Path object
        ligands1 = loader.load(test_ligand_sdf)
        # Test with string
        ligands2 = loader.load(str(test_ligand_sdf))
        
        assert len(ligands1) == len(ligands2)
        assert ligands1[0].name == ligands2[0].name
    
    def test_load_from_smiles_file_invalid_smiles_raises_error(self, temp_dir):
        """Test that invalid SMILES in SMILES file raises ValueError."""
        smi_file = temp_dir / "ligands.smi"
        with open(smi_file, 'w') as f:
            f.write("c1ccccc1 benzene\n")
            f.write("INVALID_SMILES invalid\n")
        
        loader = LigandLoader()
        with pytest.raises(ValueError):
            loader.load(smi_file)
    
    def test_load_from_sdf_no_name_property_raises_error(self, temp_dir):
        """Test that SDF molecule without _Name property raises ValueError when use_stem=False."""
        # Create an SDF file with a molecule without _Name property
        sdf_file = temp_dir / "test.sdf"
        mol = Chem.MolFromSmiles("c1ccccc1")
        with Chem.SDWriter(str(sdf_file)) as writer:
            writer.write(mol)
        
        loader = LigandLoader()
        ligands = loader.load(sdf_file, name_from_stem=False)
        assert ligands[0].name == ''
    
    def test_load_from_rdkit_none_molecule_raises_error(self):
        """Test that None molecule in RDKit list raises an error."""
        mol1 = Chem.MolFromSmiles("c1ccccc1")
        mol1.SetProp("_Name", "benzene")
        
        loader = LigandLoader()
        # None molecule will cause an error when trying to process it
        with pytest.raises((ValueError, AttributeError, TypeError)):
            loader.load([mol1, None])
    
    def test_load_from_sdf_none_molecule_raises_error(self, temp_dir):
        """Test that None molecule in SDF raises ValueError."""
        # Create an invalid SDF file that would result in None molecule
        # This is tricky - we'll create a file that fails to parse
        sdf_file = temp_dir / "invalid.sdf"
        sdf_file.write_bytes(b"Invalid SDF content\n")
        
        loader = LigandLoader()
        # This should raise ValueError because the first molecule is None
        with pytest.raises(ValueError):
            loader.load(sdf_file)
