import os
from pathlib import Path
from rdkit import Chem
from .base import SmallMoleculeForceField
from .utils import process_prmtop


class CustomForceField(SmallMoleculeForceField):
    """
    Custom force field parameterizer using pre-parameterized structures.
    
    This class allows using a pre-existing parameterized structure (e.g., from
    a prmtop file) and applying it to new ligand coordinates. This is useful
    when you have already parameterized a molecule and want to use the same
    parameters with different conformations or similar molecules.
    
    Parameters
    ----------
    custom_ff : os.PathLike
        Path to a pre-parameterized force field file. This should be a file
        that parmed can load (e.g., .prmtop, .top, .gro, etc.). The topology
        and parameters from this file will be reused.
    overwrite : bool, default True
        Whether to overwrite existing output files if they exist.
    
    Attributes
    ----------
    overwrite : bool
        Whether to overwrite existing files.
    parmed_struct : parmed.Structure
        ParmEd structure object loaded from the custom force field file.
    
    Examples
    --------
    >>> # Use a pre-parameterized prmtop file
    >>> custom = CustomForceField('template.prmtop')
    >>> custom.parametrize('new_ligand.sdf', wdir='./output')
    
    See Also
    --------
    :class:`GAFF` : GAFF-based parameterizer.
    :class:`OpenFF` : OpenFF-based parameterizer.
    """
    
    def __init__(self, custom_ff: os.PathLike, overwrite: bool = True):
        import parmed
        self.overwrite = overwrite
        self.parmed_struct = parmed.load_file(custom_ff)
    
    @process_prmtop
    def parametrize(self, ligand_file: os.PathLike, wdir: os.PathLike | None = None):
        """
        Apply custom force field parameters to a ligand structure.
        
        This method takes the topology and parameters from the pre-loaded
        custom force field and applies it to the coordinates from the input
        ligand file. The output files use the same topology/parameters but
        with new coordinates.
        
        Parameters
        ----------
        ligand_file : os.PathLike
            Path to input ligand structure file. Must be an SDF file. The
            coordinates from this file will be used, but the topology and
            parameters come from the custom force field.
        wdir : os.PathLike, optional
            Working directory for output files. If None, uses current directory.
            Output files include:
            
            * ``{stem}.prmtop``: AMBER topology file
            * ``{stem}.inpcrd``: AMBER coordinate file
            * ``{stem}.xml``: OpenMM force field XML (generated by :func:`easybfe.smff.utils.process_prmtop`)
            * ``{stem}.pdb``: PDB structure file (generated by :func:`easybfe.smff.utils.process_prmtop`)
        
        Raises
        ------
        RuntimeError
            If the ligand file cannot be parsed or if the number of atoms
            doesn't match the custom force field topology.
        AssertionError
            If energy validation fails (raised by :func:`easybfe.smff.utils.process_prmtop` decorator).
        
        Notes
        -----
        This method assumes that the input ligand has the same number of atoms
        and connectivity as the custom force field structure. The coordinates
        are extracted from the SDF file and applied to the pre-loaded topology.
        
        The method is decorated with :func:`easybfe.smff.utils.process_prmtop`, which validates
        the conversion by comparing energies.
        
        See Also
        --------
        :func:`easybfe.smff.utils.process_prmtop` : Decorator that validates parameter conversion.
        """
        prmtop_path = os.path.join(wdir, Path(ligand_file).stem + '.prmtop')
        inpcrd_path = os.path.join(wdir, Path(ligand_file).stem + '.inpcrd')
        positions = Chem.SDMolSupplier(ligand_file, removeHs=False)[0].GetConformer().GetPositions()
        self.parmed_struct.coordinates = positions
        self.parmed_struct.save(prmtop_path, overwrite=self.overwrite)
        self.parmed_struct.save(inpcrd_path, overwrite=self.overwrite)
