import os
from pathlib import Path
from rdkit import Chem
import parmed
from openff.toolkit import Molecule, Topology
from openmmforcefields.generators import SMIRNOFFTemplateGenerator
import openmm.app as app

from .base import SmallMoleculeForceField
from .utils import process_prmtop


class OpenFF(SmallMoleculeForceField):
    """
    OpenFF-based small molecule force field parameterizer.
    
    This class generates force field parameters using the Open Force Field
    (OpenFF) initiative's SMIRNOFF-based force fields. It uses the OpenFF
    toolkit to assign parameters and generate AMBER and GROMACS topology files.
    
    Parameters
    ----------
    forcefield : str, default 'openff-2.1.0'
        Name of the OpenFF force field to use (e.g., 'openff-2.1.0',
        'openff-2.0.0', 'openff-1.3.0').
    charge_method : str, default 'bcc'
        Method for partial charge assignment. Options:
        
        * 'bcc': AM1-BCC charges (mapped to 'am1bcc' in OpenFF)
        * 'gas': Gasteiger charges (mapped to 'gasteiger' in OpenFF)
        * Other: Passed directly to OpenFF toolkit
    
    Attributes
    ----------
    forcefield : str
        OpenFF force field name being used.
    charge_method : str
        Charge assignment method (after mapping).
    top : openmm.app.Topology
        OpenMM topology object (set after parametrization).
    system : openmm.System
        OpenMM system object (set after parametrization).
    struct : parmed.Structure
        ParmEd structure object (set after parametrization).
    
    Examples
    --------
    >>> openff = OpenFF(forcefield='openff-2.1.0', charge_method='bcc')
    >>> openff.parametrize('ligand.sdf', wdir='./output')
    >>> # Access generated structure
    >>> struct = openff.struct
    
    See Also
    --------
    :class:`GAFF` : GAFF-based parameterizer.
    :class:`CustomForceField` : Custom force field parameterizer.
    """
    
    def __init__(self, forcefield: str = 'openff-2.1.0', charge_method: str = 'bcc'):
        self.forcefield = forcefield

        if charge_method == 'gas':
            self.charge_method = 'gasteiger'
        elif charge_method == 'bcc':
            self.charge_method = 'am1bcc'
        else:
            self.charge_method = charge_method
        
    @process_prmtop
    def parametrize(self, ligand_file: os.PathLike, wdir: os.PathLike | None = None):
        """
        Generate OpenFF force field parameters for a ligand.
        
        This method uses the OpenFF toolkit to assign SMIRNOFF-based force
        field parameters to the ligand molecule. It generates AMBER and
        GROMACS topology files, as well as OpenMM system objects.
        
        Parameters
        ----------
        ligand_file : os.PathLike
            Path to input ligand structure file. Supported formats: .mol,
            .sdf, or .mol2.
        wdir : os.PathLike, optional
            Working directory for output files. If None, uses current directory.
            Output files include:
            
            * ``{stem}.prmtop``: AMBER topology file
            * ``{stem}.inpcrd``: AMBER coordinate file
            * ``{stem}.top``: GROMACS topology file
            * ``{stem}.xml``: OpenMM force field XML (generated by :func:`easybfe.smff.utils.process_prmtop`)
            * ``{stem}.pdb``: PDB structure file (generated by :func:`easybfe.smff.utils.process_prmtop`)
        
        Raises
        ------
        RuntimeError
            If molecule parsing fails, stereochemistry assignment fails, or
            if parameter assignment fails.
        AssertionError
            If energy validation fails (raised by :func:`easybfe.smff.utils.process_prmtop` decorator).
        
        Notes
        -----
        This method:
        
        1. Parses the input file using RDKit
        2. Assigns stereochemistry using RDKit
        3. Converts to OpenFF Molecule object
        4. Assigns partial charges using the specified method
        5. Generates SMIRNOFF parameters using the specified force field
        6. Creates OpenMM system and ParmEd structure
        7. Saves topology files in multiple formats
        
        The method sets `self.top`, `self.system`, and `self.struct` attributes
        after successful parametrization.
        
        The method is decorated with :func:`easybfe.smff.utils.process_prmtop`, which validates
        the conversion by comparing energies.
        
        See Also
        --------
        :func:`easybfe.smff.utils.process_prmtop` : Decorator that validates parameter conversion.
        """
        ligand_file = Path(ligand_file).resolve()
        wdir = Path(wdir).resolve()
        suffix = ligand_file.suffix
        if suffix == ".mol":
            mol = Chem.MolFromMolFile(str(ligand_file), removeHs=False)
        elif suffix == ".sdf":
            mol = Chem.SDMolSupplier(str(ligand_file), removeHs=False)[0]
        elif suffix == ".mol2":
            mol = Chem.MolFromMol2File(str(ligand_file), removeHs=False)
        else:
            mol = None
        Chem.AssignStereochemistry(mol, cleanIt=True, force=True)
        off_mol = Molecule.from_rdkit(mol, allow_undefined_stereo=True, hydrogens_are_explicit=True)
        off_mol.assign_partial_charges(self.charge_method, use_conformers=off_mol.conformers)
        generator = SMIRNOFFTemplateGenerator(molecules=[off_mol], forcefield=self.forcefield).generator
        ff = app.ForceField()
        ff.registerTemplateGenerator(generator)
        top = Topology.from_molecules(off_mol).to_openmm()
        system = ff.createSystem(top, constraints=None, rigidWater=False)
        struct = parmed.openmm.load_topology(top, system, xyz=mol.GetConformer().GetPositions())
        struct.residues[0].name = 'MOL'
        struct.save(str(wdir / f'{ligand_file.stem}.top'), overwrite=True, combine='all')
        struct.save(str(wdir / f'{ligand_file.stem}.prmtop'), overwrite=True)
        struct.save(str(wdir / f'{ligand_file.stem}.inpcrd'), overwrite=True)
        self.top = top
        self.system = system
        self.struct = struct
        